### ISSUE TITLE
Some problem accessing "Code Syntax > Colorize"

### ISSUE THREAD

**Issue by VinGarcia** [floitsch/syntax-addon#6]
Hello @floitsch,

this plugin is a great idea, but I was not able to use it yet, maybe you can help me with that.

I installed it on my slides presentation, pasted some code between triple backticks and specified the language right after the backticks as in the examples.

Then I found the "Add-ons > Code Syntax > Help" option clicked on it and I saw the following message:

> Create code spans and code segments by enclosing text in single or triple back-ticks. Then choose "Code Syntax > Colorize".

However, I can see no "Code Syntax > Colorize" option anywhere.

When I click on "Add-ons > Code Syntax" the only option I see is the "Help" option.

I am unsure if I just didn't find it or if it's something else.

If you can help me with this it would be awesome. Thank you.

**Comment by floitsch** [comment]
Interesting.
I just created a fresh slides document and here is how the menu should look like:
![image](https://user-images.githubusercontent.com/1731210/192996477-2e125d50-0dc1-4ac0-9408-5fc138192fa6.png)

I have had one anonymous review comment reporting the issue you have, but I couldn't follow up (since there was no way to reply). At the very least it seems like it's not just an isolated problem with your setup.

I will run some experiments (with different accounts), ... If I don't find anything, I will try to come up with some good questions for you (if you don't mind).

**Comment by VinGarcia** [comment]
Sure, thanks.

I will keep checking this conversation, although I might take some time to reply.

**Comment by VinGarcia** [comment]
Uhmm, I actually just checked it again and the menu is showing up now. So it was either something you did or this might an intermittent error, or maybe something that only happens right after a user installs it for the first time 🤔

**Comment by VinGarcia** [comment]
(btw, we can keep this ticket open in case you want to ask me more questions)

**Comment by floitsch** [comment]
Since the problem disappeared it's unlikely we can get more information.
I will close the issue.
Thanks for reporting and trying to improve things.
